"""Alembic environment.

Reads the database URL from application settings rather than alembic.ini, so
there is exactly one place the connection string is configured and a migration
can never run against a different database from the app.
"""

from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from app.core.config import get_settings

# Importing the models registers every table on Base.metadata, which is what
# autogenerate compares the live database against.
from app.repositories.models import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

config.set_main_option("sqlalchemy.url", get_settings().database_url)

target_metadata = Base.metadata

#: Tables TimescaleDB and PostGIS create for their own use. Autogenerate would
#: otherwise see them as unmanaged and try to drop them.
EXCLUDED_TABLES = frozenset({"spatial_ref_sys"})

#: Schemas owned by extensions, excluded for the same reason.
EXCLUDED_SCHEMAS = frozenset(
    {
        "_timescaledb_catalog",
        "_timescaledb_internal",
        "_timescaledb_config",
        "timescaledb_information",
    }
)


def include_object(
    obj: object,
    name: str | None,
    type_: str,
    reflected: bool,
    compare_to: object,
) -> bool:
    """Keep extension-owned objects out of autogenerated migrations."""
    if type_ == "table":
        schema = getattr(obj, "schema", None)
        if schema in EXCLUDED_SCHEMAS:
            return False
        if name in EXCLUDED_TABLES:
            return False
    return True


def run_migrations_offline() -> None:
    """Emit SQL without connecting, for review or manual application."""
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Apply migrations against a live connection."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
            compare_type=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
