"""create ingestion tables

Revision ID: 06e89bd5294d
Revises:
Create Date: 2026-09-10 21:31:08.421897

"""

from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "06e89bd5294d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fire_detections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("h3_cell", sa.String(length=15), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("frp_mw", sa.Float(), nullable=False),
        sa.Column("brightness_k", sa.Float(), nullable=True),
        sa.Column("is_daytime", sa.Boolean(), nullable=False),
        sa.Column("satellite", sa.String(length=32), nullable=False),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 1", name="ck_fire_confidence_range"),
        sa.CheckConstraint("frp_mw >= 0", name="ck_fire_frp_non_negative"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "observed_at", "h3_cell", "frp_mw", "satellite", name="uq_fire_detection_identity"
        ),
    )
    op.create_index(
        "ix_fire_detections_geom",
        "fire_detections",
        ["geom"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        op.f("ix_fire_detections_h3_cell"), "fire_detections", ["h3_cell"], unique=False
    )
    op.create_index("ix_fire_observed_at", "fire_detections", ["observed_at"], unique=False)
    op.create_table(
        "pollution_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "industry",
                "landfill",
                "brick_kiln",
                "construction",
                "road_segment",
                "crop_residue_fire",
                "waste_burning",
                "thermal_power",
                name="source_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("h3_cell", sa.String(length=15), nullable=False),
        sa.Column("emission_prior", sa.Float(), nullable=False),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("emission_prior >= 0", name="ck_source_prior_non_negative"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_pollution_sources_geom",
        "pollution_sources",
        ["geom"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        op.f("ix_pollution_sources_h3_cell"), "pollution_sources", ["h3_cell"], unique=False
    )
    op.create_table(
        "stations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("source_station_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column(
            "tier",
            sa.Enum("reference", "low_cost", "citizen", "satellite", name="station_tier"),
            nullable=False,
        ),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("h3_cell", sa.String(length=15), nullable=False),
        sa.Column("operator", sa.String(length=128), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "source_station_id", name="uq_station_source_identity"),
    )
    op.create_index("ix_stations_geom", "stations", ["geom"], unique=False, postgresql_using="gist")
    op.create_index(op.f("ix_stations_h3_cell"), "stations", ["h3_cell"], unique=False)
    op.create_table(
        "weather_observations",
        sa.Column("h3_cell", sa.String(length=15), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("wind_u", sa.Float(), nullable=False),
        sa.Column("wind_v", sa.Float(), nullable=False),
        sa.Column("temperature_c", sa.Float(), nullable=False),
        sa.Column("relative_humidity_pct", sa.Float(), nullable=False),
        sa.Column("pbl_height_m", sa.Float(), nullable=True),
        sa.Column("precipitation_mm", sa.Float(), nullable=False),
        sa.Column("is_forecast", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "pbl_height_m IS NULL OR pbl_height_m >= 0", name="ck_weather_pbl_range"
        ),
        sa.CheckConstraint(
            "relative_humidity_pct >= 0 AND relative_humidity_pct <= 100",
            name="ck_weather_humidity_range",
        ),
        sa.PrimaryKeyConstraint("h3_cell", "observed_at"),
    )
    op.create_index("ix_weather_observed_at", "weather_observations", ["observed_at"], unique=False)
    op.create_table(
        "measurements",
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "pollutant",
            sa.Enum("pm25", "pm10", "no2", "so2", "o3", "co", "nh3", name="pollutant"),
            nullable=False,
        ),
        sa.Column("value_raw", sa.Float(), nullable=False),
        sa.Column("value_calibrated", sa.Float(), nullable=True),
        sa.Column("calibration_model_version", sa.String(length=64), nullable=True),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column("is_plausible", sa.Boolean(), nullable=False),
        sa.CheckConstraint("value_raw >= 0", name="ck_measurement_non_negative"),
        sa.ForeignKeyConstraint(["station_id"], ["stations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("station_id", "observed_at", "pollutant"),
    )
    op.create_index("ix_measurements_observed_at", "measurements", ["observed_at"], unique=False)
    op.create_index(
        "ix_measurements_pollutant_time", "measurements", ["pollutant", "observed_at"], unique=False
    )
    # ### end Alembic commands ###

    # TimescaleDB hypertables. Autogenerate cannot know about these: they are a
    # storage-layer transform, not a schema difference. Both tables are
    # append-heavy and always queried over a time window, which is exactly the
    # access pattern chunking by time exists for.
    op.execute(
        "SELECT create_hypertable('measurements', by_range('observed_at'), if_not_exists => TRUE)"
    )
    op.execute(
        "SELECT create_hypertable('weather_observations', by_range('observed_at'), "
        "if_not_exists => TRUE)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_measurements_pollutant_time", table_name="measurements")
    op.drop_index("ix_measurements_observed_at", table_name="measurements")
    op.drop_table("measurements")
    op.drop_index("ix_weather_observed_at", table_name="weather_observations")
    op.drop_table("weather_observations")
    op.drop_index(op.f("ix_stations_h3_cell"), table_name="stations")
    op.drop_index("ix_stations_geom", table_name="stations", postgresql_using="gist")
    op.drop_table("stations")
    op.drop_index(op.f("ix_pollution_sources_h3_cell"), table_name="pollution_sources")
    op.drop_index(
        "ix_pollution_sources_geom", table_name="pollution_sources", postgresql_using="gist"
    )
    op.drop_table("pollution_sources")
    op.drop_index("ix_fire_observed_at", table_name="fire_detections")
    op.drop_index(op.f("ix_fire_detections_h3_cell"), table_name="fire_detections")
    op.drop_index("ix_fire_detections_geom", table_name="fire_detections", postgresql_using="gist")
    op.drop_table("fire_detections")
    # ### end Alembic commands ###
