"""add hotspots attributions alerts and authorities

Revision ID: ee1245ae70d1
Revises: 06e89bd5294d
Create Date: 2026-09-10 23:00:05.516821

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ee1245ae70d1'
down_revision: Union[str, Sequence[str], None] = '06e89bd5294d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # `pollutant` and `source_type` were created by the ingestion migration.
    # Autogenerate cannot tell an existing type from a new one, so it emits
    # CREATE TYPE for both and the upgrade fails on the duplicate; they are
    # marked create_type=False above. `hotspot_status` and `alert_status` are
    # genuinely new and are created normally.
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('jurisdiction', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('escalation_tier', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_authorities_jurisdiction', 'authorities', ['jurisdiction'], unique=False, postgresql_using='gist')
    op.create_table('hotspots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('h3_cell', sa.String(length=15), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('pollutant', postgresql.ENUM('pm25', 'pm10', 'no2', 'so2', 'o3', 'co', 'nh3', name='pollutant', create_type=False), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('intervals', sa.Integer(), nullable=False),
    sa.Column('peak_z', sa.Float(), nullable=False),
    sa.Column('peak_residual', sa.Float(), nullable=False),
    sa.Column('peak_observed', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('candidate', 'confirmed', 'resolved', 'dismissed', name='hotspot_status'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('h3_cell', 'first_seen_at', 'pollutant', name='uq_hotspot_episode')
    )
    op.create_index('ix_hotspots_geom', 'hotspots', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_hotspots_h3_cell'), 'hotspots', ['h3_cell'], unique=False)
    op.create_index('ix_hotspots_last_seen', 'hotspots', ['last_seen_at'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotspot_id', sa.Integer(), nullable=False),
    sa.Column('authority_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('sent', 'acknowledged', 'resolved', 'escalated', name='alert_status'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['authority_id'], ['authorities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hotspot_id'], ['hotspots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotspot_id', 'authority_id', name='uq_alert_hotspot_authority')
    )
    op.create_index(op.f('ix_alerts_authority_id'), 'alerts', ['authority_id'], unique=False)
    op.create_index(op.f('ix_alerts_hotspot_id'), 'alerts', ['hotspot_id'], unique=False)
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    op.create_table('hotspot_attributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotspot_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('candidate_name', sa.String(length=256), nullable=False),
    sa.Column('source_type', postgresql.ENUM('industry', 'landfill', 'brick_kiln', 'construction', 'road_segment', 'crop_residue_fire', 'waste_burning', 'thermal_power', name='source_type', create_type=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('hours_upwind', sa.Float(), nullable=False),
    sa.Column('explanation', sa.String(length=512), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_attribution_confidence'),
    sa.ForeignKeyConstraint(['hotspot_id'], ['hotspots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['pollution_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotspot_id', 'candidate_name', name='uq_attribution_candidate')
    )
    op.create_index(op.f('ix_hotspot_attributions_hotspot_id'), 'hotspot_attributions', ['hotspot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the alerting tables and the enum types this migration created.

    ``pollutant`` and ``source_type`` are left alone: they belong to the
    ingestion migration, which drops them on its own downgrade.
    """
    op.drop_index(op.f('ix_hotspot_attributions_hotspot_id'), table_name='hotspot_attributions')
    op.drop_table('hotspot_attributions')
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_index(op.f('ix_alerts_hotspot_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_authority_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_hotspots_last_seen', table_name='hotspots')
    op.drop_index(op.f('ix_hotspots_h3_cell'), table_name='hotspots')
    op.drop_index('ix_hotspots_geom', table_name='hotspots', postgresql_using='gist')
    op.drop_table('hotspots')
    op.drop_index('ix_authorities_jurisdiction', table_name='authorities', postgresql_using='gist')
    op.drop_table('authorities')

    op.execute("DROP TYPE IF EXISTS alert_status")
    op.execute("DROP TYPE IF EXISTS hotspot_status")
