/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness and upstream configuration
         * @description Report that the service is up and which upstreams are configured.
         */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest reading at every station
         * @description Return the most recent reading for each station, worst first.
         */
        get: operations["list_stations_v1_stations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/hotspots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Locations dirtier than their neighbourhood predicts
         * @description Detect hotspots over a recent window and rank candidate sources.
         */
        get: operations["list_hotspots_v1_hotspots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forecast/corridor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Concentration outlook along a route
         * @description Forecast concentrations along a corridor.
         */
        get: operations["corridor_forecast_v1_forecast_corridor_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AttributionResponse
         * @description A ranked candidate explanation for a hotspot.
         */
        AttributionResponse: {
            /** Name */
            name: string;
            source_type: components["schemas"]["SourceType"];
            position: components["schemas"]["Position"];
            /**
             * Confidence
             * @description Plausibility, not proof. Candidates are ranked, never asserted: naming the wrong operator is worse than naming nobody.
             */
            confidence: number;
            /** Distance M */
            distance_m: number;
            /** Hours Upwind */
            hours_upwind: number;
            /** Explanation */
            explanation: string;
        };
        /**
         * CorridorForecastResponse
         * @description A corridor outlook.
         */
        CorridorForecastResponse: {
            pollutant: components["schemas"]["Pollutant"];
            /** Horizon Hours */
            horizon_hours: number;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /**
             * Method
             * @description Which estimator produced this. Climatological, because it beat every learned model on a temporal holdout.
             */
            method: string;
            /** Point Count */
            point_count: number;
            /** Points */
            points: components["schemas"]["ForecastPointResponse"][];
        };
        /**
         * ForecastPointResponse
         * @description A forecast for one point along a corridor.
         */
        ForecastPointResponse: {
            position: components["schemas"]["Position"];
            /** Distance Along Km */
            distance_along_km: number;
            /**
             * Target Time
             * Format: date-time
             */
            target_time: string;
            /** Value */
            value: number;
            /**
             * Uncertainty
             * @description Expected absolute error, measured on a temporal holdout.
             */
            uncertainty: number;
            /**
             * Upper Bound
             * @description Value plus uncertainty, which is what a precautionary decision uses.
             */
            upper_bound: number;
            /** Category */
            category: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Service liveness and configuration summary.
         */
        HealthResponse: {
            /**
             * Status
             * @description Liveness indicator.
             * @constant
             */
            status: "ok";
            /**
             * Environment
             * @description Deployment environment name.
             */
            environment: string;
            /**
             * Version
             * @description Application version.
             */
            version: string;
            /**
             * H3 Resolution
             * @description Canonical H3 analysis resolution. Nodes must agree on this to exchange models.
             */
            h3_resolution: number;
            /**
             * Upstreams
             * @description Configuration state of each upstream data source.
             */
            upstreams: components["schemas"]["UpstreamStatus"][];
        };
        /**
         * HotspotResponse
         * @description A location that stayed dirtier than its neighbourhood predicted.
         */
        HotspotResponse: {
            /** Station Id */
            station_id: number;
            /** Station Name */
            station_name: string;
            position: components["schemas"]["Position"];
            /** H3 Cell */
            h3_cell: string;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Duration Hours */
            duration_hours: number;
            /** Intervals */
            intervals: number;
            /**
             * Peak Observed
             * @description Highest concentration during the episode.
             */
            peak_observed: number;
            /**
             * Peak Expected
             * @description What the surrounding network predicted at that moment.
             */
            peak_expected: number;
            /**
             * Peak Excess
             * @description Observed minus expected. This is the quantity that locates a source.
             */
            peak_excess: number;
            /**
             * Peak Z
             * @description Excess in units of the expected error at this location.
             */
            peak_z: number;
            /** Attributions */
            attributions: components["schemas"]["AttributionResponse"][];
            /**
             * Trajectory Unavailable
             * @description True when the air was calm and no back-trajectory could be traced. Distinguishes 'nothing explains this' from 'we could not look'.
             */
            trajectory_unavailable: boolean;
        };
        /**
         * HotspotsResponse
         * @description Hotspots detected over a recent window.
         */
        HotspotsResponse: {
            pollutant: components["schemas"]["Pollutant"];
            /** Window Hours */
            window_hours: number;
            /** Hotspot Count */
            hotspot_count: number;
            /** Hotspots */
            hotspots: components["schemas"]["HotspotResponse"][];
        };
        /**
         * Pollutant
         * @description Pollutants in the CPCB National AQI.
         *
         *     Values are the canonical identifiers used in the database, the API and the
         *     interoperability envelope, so they must stay stable across versions.
         * @enum {string}
         */
        Pollutant: "pm25" | "pm10" | "no2" | "so2" | "o3" | "co" | "nh3";
        /**
         * Position
         * @description A WGS84 position, in GeoJSON order.
         */
        Position: {
            /** Longitude */
            longitude: number;
            /** Latitude */
            latitude: number;
        };
        /**
         * SourceType
         * @description Categories in the pollution source registry, used for attribution.
         * @enum {string}
         */
        SourceType: "industry" | "landfill" | "brick_kiln" | "construction" | "road_segment" | "crop_residue_fire" | "waste_burning" | "thermal_power";
        /**
         * StationReadingResponse
         * @description A station's most recent reading.
         */
        StationReadingResponse: {
            /** Station Id */
            station_id: number;
            /** Name */
            name: string;
            position: components["schemas"]["Position"];
            /** H3 Cell */
            h3_cell: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Value
             * @description Concentration in the pollutant's storage unit.
             */
            value: number;
            /** Unit */
            unit: string;
            /**
             * Aqi
             * @description CPCB sub-index for this pollutant alone.
             */
            aqi: number;
            /**
             * Category
             * @description CPCB band name for the sub-index.
             */
            category: string;
        };
        /**
         * StationsResponse
         * @description Latest readings across the network.
         */
        StationsResponse: {
            pollutant: components["schemas"]["Pollutant"];
            /** Station Count */
            station_count: number;
            /** Readings */
            readings: components["schemas"]["StationReadingResponse"][];
        };
        /**
         * UpstreamStatus
         * @description Whether one upstream data source is usable.
         *
         *     ``configured`` reports only that a credential is present. It deliberately
         *     does not call the upstream: a health check that fans out to four third-party
         *     APIs fails whenever any of them is slow, which makes it useless as a liveness
         *     probe.
         */
        UpstreamStatus: {
            /**
             * Provider
             * @description Human-readable provider name.
             */
            provider: string;
            /**
             * Configured
             * @description Whether a credential is present for this provider.
             */
            configured: boolean;
            /**
             * Required Env Var
             * @description Environment variable that supplies the credential.
             */
            required_env_var: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_stations_v1_stations_get: {
        parameters: {
            query?: {
                pollutant?: components["schemas"]["Pollutant"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_hotspots_v1_hotspots_get: {
        parameters: {
            query?: {
                pollutant?: components["schemas"]["Pollutant"];
                window_hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HotspotsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    corridor_forecast_v1_forecast_corridor_get: {
        parameters: {
            query: {
                /** @description Corridor vertices as lon,lat pairs separated by semicolons, for example '77.03,28.59;77.21,28.61;77.32,28.65'. */
                points: string;
                pollutant?: components["schemas"]["Pollutant"];
                horizon_hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorridorForecastResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
